-- 시퀀스 생성
CREATE SEQUENCE PRODUCT_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE PRODUCTION_ORDER_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE ORDER_DETAIL_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE INVENTORY_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE PRODUCTION_HISTORY_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE PRODUCT_DOCUMENT_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE PRODUCT_SPEC_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE QUALITY_INSPECTION_SEQ START WITH 1 INCREMENT BY 1;

-- PRODUCT 테이블
CREATE TABLE PRODUCT (
    PRODUCT_ID NUMBER(19) PRIMARY KEY,
    PRODUCT_CODE VARCHAR2(50) UNIQUE NOT NULL,
    PRODUCT_NAME VARCHAR2(200) NOT NULL,
    UNIT_PRICE NUMBER(15,2),
    CREATED_DATE DATE
);

-- PRODUCTION_ORDER 테이블
CREATE TABLE PRODUCTION_ORDER (
    ORDER_ID NUMBER(19) PRIMARY KEY,
    ORDER_NO VARCHAR2(50) UNIQUE NOT NULL,
    ORDER_DATE DATE NOT NULL,
    TOTAL_AMOUNT NUMBER(15,2),
    NOTES CLOB
);

-- ORDER_DETAIL 테이블
CREATE TABLE ORDER_DETAIL (
    DETAIL_ID NUMBER(19) PRIMARY KEY,
    ORDER_ID NUMBER(19) NOT NULL,
    PRODUCT_ID NUMBER(19) NOT NULL,
    QUANTITY NUMBER(10) NOT NULL,
    UNIT_PRICE NUMBER(15,2),
    LINE_AMOUNT NUMBER(15,2),
    CONSTRAINT FK_DETAIL_ORDER FOREIGN KEY (ORDER_ID) REFERENCES PRODUCTION_ORDER(ORDER_ID),
    CONSTRAINT FK_DETAIL_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID)
);

-- INVENTORY 테이블
CREATE TABLE INVENTORY (
    INVENTORY_ID NUMBER(19) PRIMARY KEY,
    PRODUCT_ID NUMBER(19) UNIQUE NOT NULL,
    QUANTITY NUMBER(10) NOT NULL,
    LAST_UPDATED TIMESTAMP,
    VERSION NUMBER(19),
    CONSTRAINT FK_INVENTORY_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID)
);

-- PRODUCTION_HISTORY 테이블 (계층 구조)
CREATE TABLE PRODUCTION_HISTORY (
    HISTORY_ID NUMBER(19) PRIMARY KEY,
    ORDER_ID NUMBER(19) NOT NULL,
    PARENT_ID NUMBER(19),
    PROCESS_NAME VARCHAR2(100),
    PROCESS_DATE TIMESTAMP,
    CONSTRAINT FK_HISTORY_ORDER FOREIGN KEY (ORDER_ID) REFERENCES PRODUCTION_ORDER(ORDER_ID),
    CONSTRAINT FK_HISTORY_PARENT FOREIGN KEY (PARENT_ID) REFERENCES PRODUCTION_HISTORY(HISTORY_ID)
);

-- PRODUCT_DOCUMENT 테이블 (LOB)
CREATE TABLE PRODUCT_DOCUMENT (
    DOC_ID NUMBER(19) PRIMARY KEY,
    PRODUCT_ID NUMBER(19) NOT NULL,
    DOC_NAME VARCHAR2(200),
    DOC_CONTENT CLOB,
    DOC_FILE BLOB,
    EXTERNAL_FILE VARCHAR2(500),
    CREATED_DATE DATE,
    CONSTRAINT FK_DOCUMENT_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID)
);

-- PRODUCT_SPEC 테이블 (XMLTYPE)
CREATE TABLE PRODUCT_SPEC (
    SPEC_ID NUMBER(19) PRIMARY KEY,
    PRODUCT_ID NUMBER(19) UNIQUE NOT NULL,
    SPEC_XML CLOB,
    VERSION VARCHAR2(20),
    CREATED_DATE DATE,
    CONSTRAINT FK_SPEC_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID)
);

-- QUALITY_INSPECTION 테이블 (파티션 테이블 - Range by Month + List by Result)
CREATE TABLE QUALITY_INSPECTION (
    INSPECTION_ID NUMBER(19) NOT NULL,
    PRODUCT_ID NUMBER(19) NOT NULL,
    ORDER_ID NUMBER(19),
    INSPECTION_DATE DATE NOT NULL,
    RESULT VARCHAR2(20) NOT NULL,
    DEFECT_COUNT NUMBER(10) DEFAULT 0,
    INSPECTOR_NAME VARCHAR2(100),
    NOTES CLOB,
    CONSTRAINT PK_QUALITY_INSPECTION PRIMARY KEY (INSPECTION_ID, INSPECTION_DATE, RESULT),
    CONSTRAINT FK_INSPECTION_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID),
    CONSTRAINT FK_INSPECTION_ORDER FOREIGN KEY (ORDER_ID) REFERENCES PRODUCTION_ORDER(ORDER_ID),
    CONSTRAINT CHK_RESULT CHECK (RESULT IN ('PASS', 'FAIL', 'PENDING'))
)
PARTITION BY RANGE (INSPECTION_DATE)
SUBPARTITION BY LIST (RESULT)
SUBPARTITION TEMPLATE (
    SUBPARTITION sp_pass VALUES ('PASS'),
    SUBPARTITION sp_fail VALUES ('FAIL'),
    SUBPARTITION sp_pending VALUES ('PENDING')
)
(
    PARTITION p_202412 VALUES LESS THAN (TO_DATE('2025-01-01', 'YYYY-MM-DD')),
    PARTITION p_202501 VALUES LESS THAN (TO_DATE('2025-02-01', 'YYYY-MM-DD')),
    PARTITION p_202502 VALUES LESS THAN (TO_DATE('2025-03-01', 'YYYY-MM-DD')),
    PARTITION p_202503 VALUES LESS THAN (TO_DATE('2025-04-01', 'YYYY-MM-DD')),
    PARTITION p_202504 VALUES LESS THAN (TO_DATE('2025-05-01', 'YYYY-MM-DD')),
    PARTITION p_202505 VALUES LESS THAN (TO_DATE('2025-06-01', 'YYYY-MM-DD')),
    PARTITION p_202506 VALUES LESS THAN (TO_DATE('2025-07-01', 'YYYY-MM-DD')),
    PARTITION p_202507 VALUES LESS THAN (TO_DATE('2025-08-01', 'YYYY-MM-DD')),
    PARTITION p_202508 VALUES LESS THAN (TO_DATE('2025-09-01', 'YYYY-MM-DD')),
    PARTITION p_202509 VALUES LESS THAN (TO_DATE('2025-10-01', 'YYYY-MM-DD')),
    PARTITION p_202510 VALUES LESS THAN (TO_DATE('2025-11-01', 'YYYY-MM-DD')),
    PARTITION p_202511 VALUES LESS THAN (TO_DATE('2025-12-01', 'YYYY-MM-DD')),
    PARTITION p_202512 VALUES LESS THAN (TO_DATE('2026-01-01', 'YYYY-MM-DD')),
    PARTITION p_max VALUES LESS THAN (MAXVALUE)
);

-- 인덱스 생성 (UNIQUE 제약 조건이 있는 컬럼은 자동 인덱스 생성되므로 제외)
-- CREATE INDEX IDX_PRODUCT_CODE ON PRODUCT(PRODUCT_CODE); -- UNIQUE 제약으로 자동 생성
CREATE INDEX IDX_ORDER_DATE ON PRODUCTION_ORDER(ORDER_DATE);
CREATE INDEX IDX_DETAIL_ORDER ON ORDER_DETAIL(ORDER_ID);
CREATE INDEX IDX_DETAIL_PRODUCT ON ORDER_DETAIL(PRODUCT_ID);
-- CREATE INDEX IDX_INVENTORY_PRODUCT ON INVENTORY(PRODUCT_ID); -- UNIQUE 제약으로 자동 생성
CREATE INDEX IDX_HISTORY_ORDER ON PRODUCTION_HISTORY(ORDER_ID);
CREATE INDEX IDX_HISTORY_PARENT ON PRODUCTION_HISTORY(PARENT_ID);
CREATE INDEX IDX_DOCUMENT_PRODUCT ON PRODUCT_DOCUMENT(PRODUCT_ID);
CREATE INDEX IDX_INSPECTION_PRODUCT ON QUALITY_INSPECTION(PRODUCT_ID) LOCAL;
CREATE INDEX IDX_INSPECTION_ORDER ON QUALITY_INSPECTION(ORDER_ID) LOCAL;
CREATE INDEX IDX_INSPECTION_DATE ON QUALITY_INSPECTION(INSPECTION_DATE) LOCAL;

COMMIT;

EXIT;
